spring:
  application:
    name: aws-demo
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  # OAuth2 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code

        provider:
          google:
            # prompt 파라미터를 URL에 직접 추가
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account    # 사용자가 로그인할 때 브라우저가 이동하는 URL(Google 로그인 화면)
            token-uri: https://www.googleapis.com/oauth2/v4/token                                    # 로그인 완료 후 서버가 Google에게 access token 전송 요청을 보내는 URL
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo                             # 발급받은 token으로 사용자 정보(email, name 등)를 가져오는 API
            user-name-attribute: sub                                                                 # 사용자 정보 중 고유 식별자로 쓸 필드명(sub = Google의 unique user id)

# CORS 설정
cors:
  allowed-origins: http://localhost:3000

# 프론트엔드 URL
frontend:
  url: http://localhost:3000

# 카카오 맵
kakao:
  map:
    api-key: ${KAKAO_MAP_API_KEY}
    base-url: https://dapi.kakao.com

# 토스
toss:
  secret-key: ${TOSS_SECRET_KEY}
  api:
    url:
      confirm: https://api.tosspayments.com/v1/payments/confirm

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.core.env: DEBUG
    org.springframework.boot.context.config: DEBUG
    com.zaxxer.hikari: DEBUG