spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  cloud:
    aws:
      region:
        static: ${AWS_REGION}  # .env에서 자동으로 읽힘
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      s3:
        bucket: ${AWS_S3_BUCKET}
      stack:
        auto: false  # CloudFormation 비활성화

springdoc:
  api-docs.enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    display-request-duration: true
    tryItOutEnabled: true