spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs.enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    display-request-duration: true
    tryItOutEnabled: true