name: CI

on:
  pull_request:
    branches: [ dev ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    # 1단계: MySQL Docker 컨테이너 서비스 정의 (필수)
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root  # 컨테이너 시작에 필요한 임시 비밀번호
          MYSQL_DATABASE: test_db    # 테스트 DB 이름
        ports:
          - 3306:3306                # 호스트 포트로 연결
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping || exit 1"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 20

    env:
      SPRING_PROFILES_ACTIVE: test
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle # Gradle 설정, 종속성 및 빌드 캐시를 자동으로 관리
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      # 2단계: Spring Boot 접속 정보 설정
      - name: Configure DB Connection & Redis Connection
        run: |
          # 127.0.0.1:3306으로 접속하도록 환경 변수 설정
          echo "SPRING_DATASOURCE_URL=jdbc:mysql://127.0.0.1:3306/test_db?useSSL=false&allowPublicKeyRetrieval=true" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=root" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=root" >> $GITHUB_ENV

          echo "SPRING_DATA_REDIS_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "SPRING_DATA_REDIS_PORT=6379" >> $GITHUB_ENV
          echo "SPRING_DATA_REDIS_PASSWORD=" >> $GITHUB_ENV

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Export environment variables
        run: |
          echo "TOSS_SECRET_KEY=${{ secrets.TOSS_SECRET_KEY }}" >> $GITHUB_ENV

    # check를 통해서 빌드와 테스트 동시에 진행 / test 설정을 CI에 사용
      - name: Run tests with coverage check
        run: ./gradlew clean check